config/routes.rb
Rails.application.routes.draw do
 	
  resources :expenses
  resources :attendances
  resources :prices
  resources :schedules
  resources :activities 

  devise_for :users
  resources :associates
 	get 'welcome/index'
  get 'select/index'
  get 'select/associate_management'
  get 'select/activity_management'
  get 'select/finances_management'
	root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/schedule.rb
class Schedule < ApplicationRecord
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_schedule, only: [:show, :edit, :update, :destroy]

  # GET /schedules
  # GET /schedules.json
  def index
    @schedules = Schedule.all
  end

  # GET /schedules/1
  # GET /schedules/1.json
  def show
  end

  # GET /schedules/new
  def new
    @schedule = Schedule.new
  end

  # GET /schedules/1/edit
  def edit
  end

  # POST /schedules
  # POST /schedules.json
  def create
    @schedule = Schedule.new(schedule_params)


    respond_to do |format|
      if @schedule.save
        @activity = Activity.new(activity_params)
        @activity.schedule_id = @schedule.id

        if @activity.save
            format.html { redirect_to activities_path, notice: 'Schedule was successfully created.' }
            format.json { render :show, status: :created, location: @schedule }
        else
            format.html { render :new }
            format.json { render json: @schedule.errors, status: :unprocessable_entity }
        end
        
        format.html { redirect_to @schedule, notice: 'Schedule was successfully created.' }
        format.json { render :show, status: :created, location: @schedule }
      else
        format.html { render :new }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schedules/1
  # PATCH/PUT /schedules/1.json
  def update
    respond_to do |format|
      if @schedule.update(schedule_params)
        format.html { redirect_to @schedule, notice: 'Schedule was successfully updated.' }
        format.json { render :show, status: :ok, location: @schedule }
      else
        format.html { render :edit }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
    @schedule.destroy
    respond_to do |format|
      format.html { redirect_to schedules_url, notice: 'Schedule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schedule
      @schedule = Schedule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def schedule_params
      params.require(:schedule).permit(:day_1, :day_2, :day_3, :day_4, :day_5, :starting_time, 
        :ending_time, :name)
    end
     def activity_params
      params.require(:schedule).permit(:name, :active)
    end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/_form.html.erb
<head> 
 <%= stylesheet_link_tag "forms" %>

</head>

<%= form_with(model: schedule, local: true) do |form| %>
  <% if schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>

      <ul>
      <% schedule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<body class="background_image">
<div class="container">
  <div class="field">
    <%= form.label "Nombre*" %>
    <%= form.text_field :name, id: :activity_name, :required => true, oninvalid: 'this.setCustomValidity("Este campo no debe estar vacío.")', oninput: 'this.setCustomValidity("")'%>
  </div>
  <div class="field">
    <%= form.label "Día 1*" %>
    <%= form.select :day_1, ['L', 'M', 'W', 'J', 'V', 'S', 'D', 'N/A'] %>
  </div>
  <div class="field">
    <%= form.label "Día 2*" %>
      <%= form.select :day_2, ['L', 'M', 'W', 'J', 'V', 'S', 'D', 'N/A'] %>
  </div>
  <div class="field">
    <%= form.label "Día 3*" %>
      <%= form.select :day_3, ['L', 'M', 'W', 'J', 'V', 'S', 'D', 'N/A'] %>
  </div>
  <div class="field">
    <%= form.label "Día 4" %>
    <%= form.select :day_4, ['L', 'M', 'W', 'J', 'V', 'S', 'D', 'N/A'] %>
  </div>
  <div class="field">
    <%= form.label "Día 5" %>
      <%= form.select :day_5, ['L', 'M', 'W', 'J', 'V', 'S', 'D', 'N/A'] %>
  </div>
  <div class="field">
    <%= form.label "Hora de inicio*" %>
    <%= form.text_field :starting_time, id: :schedule_starting_time, :required => true, oninvalid: 'this.setCustomValidity("Este campo no debe estar vacío.")', oninput: 'this.setCustomValidity("")' %>
  </div>
  <div class="field">
    <%= form.label "Hora de fin*" %>
    <%= form.text_field :ending_time, id: :schedule_ending_time, :required => true, oninvalid: 'this.setCustomValidity("Este campo no debe estar vacío.")', oninput: 'this.setCustomValidity("")' %>
  </div>
    <div class="field">
    Activa <%= form.check_box :active, id: :activity_active %>
  </div>
  <br>

  <div class="actions">
    <%= form.submit 'Crear actividad', class: 'btn btn-success btn-lg btn-block' %>
  </div>
<% end %>

</div>

</body>

app/views/schedules/edit.html.erb
<div class="form_title"><h1>Editing Schedule</h1></div>

<%= render 'form', schedule: @schedule %>

<%= link_to 'Atrás', schedules_path, class: 'btn btn-success btn-lg' %>

app/views/schedules/index.html.erb
<p id="notice"><%= notice %></p>

<body class="background_image">
  <h1>Horarios</h1>

    <table class="table table-sm">
    <thead>
      <tr class="bg-success">
        <th scope="col">Actividad</th>
        <th scope="col">Día 1</th>
        <th scope="col">Día 2</th>
        <th scope="col">Día 3</th>
        <th scope="col">Día 4</th>
        <th scope="col">Día 5</th>
        <th scope="col">Hora de inicio</th>
        <th scope="col">Hora de fin</th>
        <th scope="col">Gestión</th>
        <th scope="col">  </th>
      </tr>
    </thead>
    <tbody>
      <tbody>
    <% @schedules.each do |schedule| %>
      <tr class="table-light">
        <td><%= schedule.name %></td>
        <td><%= schedule.day_1 %></td>
        <td><%= schedule.day_2 %></td>
        <td><%= schedule.day_3 %></td>
        <td><%= schedule.day_4 %></td>
        <td><%= schedule.day_5 %></td>
        <td><%= schedule.starting_time %></td>
        <td><%= schedule.ending_time %></td>
        <td><%= link_to 'Modificar', edit_schedule_path(schedule), class: 'btn btn-success btn-lg'  %></td>
        <td><%= button_to 'Eliminar', schedule, method: :delete, data: { confirm: 'Are you sure?'}, class: 'btn btn-success btn-lg'  %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>

<br>

<%= link_to 'Atrás', select_activity_management_path,  class: 'btn btn-success btn-lg'  %>

app/views/schedules/new.html.erb
<head> 
 <%= stylesheet_link_tag "forms" %>
</head>


<div class="form_title"> <h1>Crear actividad</h1></div>

<%= render 'form', schedule: @schedule %>

<%= link_to 'Atrás', select_activity_management_path,  class: 'btn btn-success btn-lg'  %>

app/views/schedules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Day 1:</strong>
  <%= @schedule.day_1 %>
</p>

<p>
  <strong>Day 2:</strong>
  <%= @schedule.day_2 %>
</p>

<p>
  <strong>Day 3:</strong>
  <%= @schedule.day_3 %>
</p>

<p>
  <strong>Day 4:</strong>
  <%= @schedule.day_4 %>
</p>

<p>
  <strong>Day 5:</strong>
  <%= @schedule.day_5 %>
</p>

<p>
  <strong>Starting time:</strong>
  <%= @schedule.starting_time %>
</p>

<p>
  <strong>Ending time:</strong>
  <%= @schedule.ending_time %>
</p>

<%= link_to 'Edit', edit_schedule_path(@schedule) %> |
<%= link_to 'Back', schedules_path %>