config/routes.rb
Rails.application.routes.draw do
 	
  resources :expenses
  resources :attendances
  resources :prices
  resources :schedules
  resources :activities 

  devise_for :users
  resources :associates
 	get 'welcome/index'
  get 'select/index'
  get 'select/associate_management'
  get 'select/activity_management'
  get 'select/finances_management'
	root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/price.rb
class Price < ApplicationRecord
end

app/controllers/prices_controller.rb
class PricesController < ApplicationController
  before_action :set_price, only: [:show, :edit, :update, :destroy]

  # GET /prices
  # GET /prices.json
  def index
    @prices = Price.all
  end

  # GET /prices/1
  # GET /prices/1.json
  def show
  end

  # GET /prices/new
  def new
    @price = Price.new

    @activities = Activity.all
    @names = Array.new

    @activities.each do |act|

      @names << act.name

    end
  end

  # GET /prices/1/edit
  def edit
  end

  # POST /prices
  # POST /prices.json
  def create
    @price = Price.new(price_params)
    @activities = Activity.all

    @names = Array.new

    @activities.each do |act|

      @names << act.name

    end

    respond_to do |format|
      if @price.save
        format.html { redirect_to prices_path, notice: 'Price was successfully created.' }
        format.json { render :show, status: :created, location: @price }
      else
        format.html { render :new }
        format.json { render json: @price.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prices/1
  # PATCH/PUT /prices/1.json
  def update
    respond_to do |format|
      if @price.update(price_params)
        format.html { redirect_to @price, notice: 'Price was successfully updated.' }
        format.json { render :show, status: :ok, location: @price }
      else
        format.html { render :edit }
        format.json { render json: @price.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prices/1
  # DELETE /prices/1.json
  def destroy
    @price.destroy
    respond_to do |format|
      format.html { redirect_to prices_url, notice: 'Price was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_price
      @price = Price.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def price_params
      params.require(:price).permit(:position, :activity, :price)
    end
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/views/prices/_form.html.erb
<%= form_with(model: price, local: true) do |form| %>
  <% if price.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(price.errors.count, "error") %> prohibited this price from being saved:</h2>

      <ul>
      <% price.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label "Posición" %>
    <%= form.text_field :position, id: :price_position %>
  </div>


  <div class="field">
    <%= form.label :activity %>
    <%= form.select(:activity, @names, :required => true) %>

  </div>
   
  </div>

  <div class="field">
    <%= form.label "Tarifa" %>
    <%= form.text_field :price, id: :price_price %>
  </div>

  <div class="actions">
    <%= form.submit "Aceptar" %>
  </div>
<% end %>

app/views/prices/edit.html.erb
<h1>Editing Price</h1>

<%= render 'form', price: @price %>

<%= link_to 'Show', @price %> |
<%= link_to 'Back', prices_path %>

app/views/prices/index.html.erb
<p id="notice"><%= notice %></p>

<head> 
 <%= stylesheet_link_tag "tables" %>
 <%= stylesheet_link_tag "buttons" %>
</head>

<h1>Tarifas</h1>

  <table id="keywords" cellspacing="0" cellpadding="0">
    <thead>
      <tr>
        <th><span>Posición</span></th>
        <th><span>Actividad</span></th>
        <th><span>Tarifa</span></th>
      </tr>
    </thead>

  <tbody>
    <% @prices.each do |price| %>
      <tr>
        <td class="lalign"><%= price.position %></td>
        <td><%= price.activity %></td>
        <td><%= price.price %></td>
        <td><%= button_to 'Modificar', edit_price_path(price), method: :get, class: 'button' %></td>
        <td><%= button_to 'Eliminar', price, method: :delete, data: { confirm: 'Are you sure?' }, class: 'button' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= button_to 'Nueva Tarifa', new_price_path, method: :get, class: 'button' %>

app/views/prices/new.html.erb
<h1>Nueva Tarifa</h1>

<%= render 'form', price: @price %>

<%= link_to 'Back', prices_path %>

app/views/prices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Position:</strong>
  <%= @price.position %>
</p>

<p>
  <strong>Activity:</strong>
  <%= @price.activity %>
</p>

<p>
  <strong>Price:</strong>
  <%= @price.price %>
</p>

<%= link_to 'Edit', edit_price_path(@price) %> |
<%= link_to 'Back', prices_path %>