config/routes.rb
Rails.application.routes.draw do
 	
  resources :expenses
  resources :attendances
  resources :prices
  resources :schedules
  resources :activities 

  devise_for :users
  resources :associates
 	get 'welcome/index'
  get 'select/index'
  get 'select/associate_management'
  get 'select/activity_management'
  get 'select/finances_management'
	root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
class Activity < ApplicationRecord
	
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/associate.rb
class Associate < ApplicationRecord
	validates :code, uniqueness: true
	validates_presence_of :name, :last_name, :code
	has_many :attendances

end

app/models/attendance.rb
class Attendance < ApplicationRecord
end

app/models/expense.rb
class Expense < ApplicationRecord
end

app/models/price.rb
class Price < ApplicationRecord
end

app/models/schedule.rb
class Schedule < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_expense, only: [:show, :edit, :update, :destroy]

  # GET /expenses
  # GET /expenses.json
  def index
    @expenses = Expense.all
  end

  # GET /expenses/1
  # GET /expenses/1.json
  def show
  end

  # GET /expenses/new
  def new
    @expense = Expense.new
  end

  # GET /expenses/1/edit
  def edit
  end

  # POST /expenses
  # POST /expenses.json
  def create
    @expense = Expense.new(expense_params)
    @expense.date = DateTime.now  

    respond_to do |format|
      if @expense.save
        format.html { redirect_to @expense, notice: 'Expense was successfully created.' }
        format.json { render :show, status: :created, location: @expense }
      else
        format.html { render :new }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expenses/1
  # PATCH/PUT /expenses/1.json
  def update
    respond_to do |format|
      if @expense.update(expense_params)
        format.html { redirect_to @expense, notice: 'Expense was successfully updated.' }
        format.json { render :show, status: :ok, location: @expense }
      else
        format.html { render :edit }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1
  # DELETE /expenses/1.json
  def destroy
    @expense.destroy
    respond_to do |format|
      format.html { redirect_to expenses_url, notice: 'Expense was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expense
      @expense = Expense.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def expense_params
      params.require(:expense).permit(:concept, :amount, :date, :receiver)
    end
end

app/controllers/prices_controller.rb
class PricesController < ApplicationController
  before_action :set_price, only: [:show, :edit, :update, :destroy]

  # GET /prices
  # GET /prices.json
  def index
    @prices = Price.all
  end

  # GET /prices/1
  # GET /prices/1.json
  def show
  end

  # GET /prices/new
  def new
    @price = Price.new

    @activities = Activity.all
    @names = Array.new

    @activities.each do |act|

      @names << act.name

    end
  end

  # GET /prices/1/edit
  def edit
  end

  # POST /prices
  # POST /prices.json
  def create
    @price = Price.new(price_params)
    @activities = Activity.all

    @names = Array.new

    @activities.each do |act|

      @names << act.name

    end

    respond_to do |format|
      if @price.save
        format.html { redirect_to prices_path, notice: 'Price was successfully created.' }
        format.json { render :show, status: :created, location: @price }
      else
        format.html { render :new }
        format.json { render json: @price.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prices/1
  # PATCH/PUT /prices/1.json
  def update
    respond_to do |format|
      if @price.update(price_params)
        format.html { redirect_to @price, notice: 'Price was successfully updated.' }
        format.json { render :show, status: :ok, location: @price }
      else
        format.html { render :edit }
        format.json { render json: @price.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prices/1
  # DELETE /prices/1.json
  def destroy
    @price.destroy
    respond_to do |format|
      format.html { redirect_to prices_url, notice: 'Price was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_price
      @price = Price.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def price_params
      params.require(:price).permit(:position, :activity, :price)
    end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_schedule, only: [:show, :edit, :update, :destroy]

  # GET /schedules
  # GET /schedules.json
  def index
    @schedules = Schedule.all
  end

  # GET /schedules/1
  # GET /schedules/1.json
  def show
  end

  # GET /schedules/new
  def new
    @schedule = Schedule.new
  end

  # GET /schedules/1/edit
  def edit
  end

  # POST /schedules
  # POST /schedules.json
  def create
    @schedule = Schedule.new(schedule_params)


    respond_to do |format|
      if @schedule.save
        @activity = Activity.new(activity_params)
        @activity.schedule_id = @schedule.id

        if @activity.save
            format.html { redirect_to activities_path, notice: 'Schedule was successfully created.' }
            format.json { render :show, status: :created, location: @schedule }
        else
            format.html { render :new }
            format.json { render json: @schedule.errors, status: :unprocessable_entity }
        end
        
        format.html { redirect_to @schedule, notice: 'Schedule was successfully created.' }
        format.json { render :show, status: :created, location: @schedule }
      else
        format.html { render :new }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schedules/1
  # PATCH/PUT /schedules/1.json
  def update
    respond_to do |format|
      if @schedule.update(schedule_params)
        format.html { redirect_to @schedule, notice: 'Schedule was successfully updated.' }
        format.json { render :show, status: :ok, location: @schedule }
      else
        format.html { render :edit }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
    @schedule.destroy
    respond_to do |format|
      format.html { redirect_to schedules_url, notice: 'Schedule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schedule
      @schedule = Schedule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def schedule_params
      params.require(:schedule).permit(:day_1, :day_2, :day_3, :day_4, :day_5, :starting_time, 
        :ending_time, :name)
    end
     def activity_params
      params.require(:schedule).permit(:name, :active)
    end
end

app/controllers/select_controller.rb
class SelectController < ApplicationController
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def index
	end
	
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/associates_helper.rb
module AssociatesHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/select_helper.rb
module SelectHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/expenses/_form.html.erb
<body class="background_image">
<%= form_with(model: expense, local: true) do |form| %>
  <% if expense.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

      <ul>
      <% expense.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="container">
  <div class="field">
    <%= form.label :concept %>
    <%= form.text_field :concept, id: :expense_concept %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.text_field :amount, id: :expense_amount %>
  </div>

  <div class="field">
    <%= form.label :receiver %>
    <%= form.text_field :receiver, id: :expense_receiver %>
  </div>

  <div class="actions">
    <%= form.submit 'Agregar Egreso' , class: 'btn btn-success btn-lg btn-block'%>
  </div>
<% end %>
</div>

</body>

app/views/expenses/edit.html.erb
<h1>Editing Expense</h1>

<%= render 'form', expense: @expense %>

<%= link_to 'Show', @expense %> |
<%= link_to 'Back', expenses_path %>

app/views/expenses/index.html.erb
<p id="notice"><%= notice %></p>
<body class="background_image">
<h1>Expenses</h1>

 <h1>Horarios</h1>

    <table class="table table-sm">
    <thead>
      <tr class="bg-success">
        <th scope="col">Concepto</th>
        <th scope="col">Cantidad</th>
        <th scope="col">Fecha</th>
        <th scope="col">Destinatario</th>
      </tr>
    </thead>
    <tbody>
      <tbody>
    <% @expenses.each do |expense| %>
      <tr class="table-light">
        <td><%= expense.concept %></td>
        <td><%= expense.amount %></td>
        <td><%= expense.date %></td>
        <td><%= expense.receiver %></td>
      </tr>
    <% end %>
    </tbody>
  </table>

<%= link_to 'Atrás', select_finances_management_path,  class: 'btn btn-success btn-lg'  %>

app/views/expenses/new.html.erb
<head> 
 <%= stylesheet_link_tag "forms" %>
</head>
<div class="form_title">

<h1>Nuevo Egreso</h1>

</div>
<%= render 'form', expense: @expense %>

<%= link_to 'Atrás', select_finances_management_path,  class: 'btn btn-success btn-lg'  %>

app/views/expenses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Concept:</strong>
  <%= @expense.concept %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @expense.amount %>
</p>

<p>
  <strong>Date:</strong>
  <%= @expense.date %>
</p>

<p>
  <strong>Receiver:</strong>
  <%= @expense.receiver %>
</p>

<%= link_to 'Edit', edit_expense_path(@expense) %> |
<%= link_to 'Back', expenses_path %>

app/views/select/activity_management.html.erb
<head> 
	
	<link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Nobile" />

</head>

<body class="background_image">

 <div class="select">

     <h2 class="menu_title"> Gestión de actividades </h2>
     <td><%= link_to 'Nueva actividad', new_schedule_path, class: 'btn btn-success btn-lg btn-block' %></td>
     <br>
     <td><%= link_to 'Ver actividades', activities_path, class: 'btn btn-success btn-lg btn-block' %></td>
     <br>
     <td><%= link_to 'Ver horarios', schedules_path, class: 'btn btn-success btn-lg btn-block' %></td>
     <br>
     <td><%= link_to 'Atrás',  select_index_path, class: 'btn btn-success btn-lg btn-block' %></td>
</div>

</body>

app/views/select/associate_management.html.erb
<head> 
	
	<link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Nobile" />

</head>
<body class="background_image">
<div class="select">
<h2 class="menu_title"> Gestión de asociados </h2>


<td><%= link_to 'Nuevo asociado',  new_associate_path, class: 'btn btn-success btn-lg btn-block' %></td>
<br>
<td><%= link_to 'Ver asociados',  associates_path, class: 'btn btn-success btn-lg btn-block' %></td>
<br>

<td><%= link_to 'Atrás',  select_index_path, class: 'btn btn-success btn-lg btn-block' %></td>
</div>
</body>

app/views/select/finances_management.html.erb
<head> 
	
	<link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Nobile" />

</head>
<body class="background_image">
<div class="select">
<h2 class="menu_title"> Gestión Financiera </h2>


<td><%= link_to 'Nuevo egreso',  new_expense_path, class: 'btn btn-success btn-lg btn-block' %></td>
<br>
<td><%= link_to 'Ver egresos',  expenses_path, class: 'btn btn-success btn-lg btn-block' %></td>
<br>

<td><%= link_to 'Atrás',  select_index_path, class: 'btn btn-success btn-lg btn-block' %></td>
</div>
</body>

app/views/select/index.html.erb
<head> 
	
   <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Nobile" />

</head>

<body class="background_image">


 <div class="select">
  <h2 class="menu_title"> Gestión </h2>

  <td><%= link_to 'Gestión de asociados',  select_associate_management_path, class: 'btn btn-success btn-lg btn-block' %></td>
  <br>
  <td><%= link_to 'Gestión de actividades', select_activity_management_path, class: 'btn btn-success btn-lg btn-block' %></td>
  <td><%= link_to 'Gestión financiera', select_finances_management_path, class: 'btn btn-success btn-lg btn-block' %></td>
  <br>

  <h2 class="menu_title"> Asistencias </h2>

  <td><%= link_to 'Nueva asistencia',  new_attendance_path,  class: 'btn btn-success btn-lg btn-block' %></td>
  <br>
  <td><%= link_to 'Ver asistencias',  attendances_path, class: 'btn btn-success btn-lg btn-block' %></td>
  <br>
  <%= link_to 'Atrás',  welcome_index_path, class: 'btn btn-success btn-lg btn-block' %>
 </div>

</body>

app/views/welcome/index.html.erb
<h2>Hello World</h2>
<p>
  The time is now: <%= Time.now %>
</p>


<td><%= link_to 'select', select_index_path %></td>