config/routes.rb
Rails.application.routes.draw do
 	
  resources :expenses
  resources :attendances
  resources :prices
  resources :schedules
  resources :activities 

  devise_for :users
  resources :associates
 	get 'welcome/index'
  get 'select/index'
  get 'select/associate_management'
  get 'select/activity_management'
  get 'select/finances_management'
	root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/associate.rb
class Associate < ApplicationRecord
	validates :code, uniqueness: true
	validates_presence_of :name, :last_name, :code
	has_many :attendances

end

app/controllers/associates_controller.rb
class AssociatesController < ApplicationController
  before_action :set_associate, only: [:show, :edit, :update, :destroy]

  # GET /associates
  # GET /associates.json
  def index
    @associates = Associate.all
  end

  # GET /associates/1
  # GET /associates/1.json
  def show
  end

  # GET /associates/new
  def new
    @associate = Associate.new
  end

  # GET /associates/1/edit
  def edit
  end

  # POST /associates
  # POST /associates.json
  def create
    @associate = Associate.new(associate_params)

    respond_to do |format|
      if @associate.save
        format.html { redirect_to associates_path, notice: 'Associate was successfully created.' }
        format.json { render :show, status: :created, location: @associate }
      else
        format.html { render :new }
        format.json { render json: @associate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /associates/1
  # PATCH/PUT /associates/1.json
  def update
    respond_to do |format|
      if @associate.update(associate_params)
        format.html { redirect_to associates_path, notice: 'Associate was successfully updated.' }
        format.json { render :show, status: :ok, location: @associate }
      else
        format.html { render :edit }
        format.json { render json: @associate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /associates/1
  # DELETE /associates/1.json
  def destroy
    @associate.destroy
    respond_to do |format|
      format.html { redirect_to associates_url, notice: 'Associate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_associate
      @associate = Associate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def associate_params
      params.require(:associate).permit(:code, :name, :position, :last_name, :sponsor, 
        :ascending_president, :ascending_tabulator, :last_payment)
    end
end

app/helpers/associates_helper.rb
module AssociatesHelper
end

app/views/associates/_form.html.erb
<head> 
 <%= stylesheet_link_tag "forms" %>
</head>
<body class="background_image">
<%= form_with(model: associate, local: true) do |form| %>
  <% if associate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(associate.errors.count, "error") %> prohibited this associate from being saved:</h2>

      <ul>
      <% associate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container">

  <div class="field">
    <%= form.label 'Código*' %>
    <%= form.text_field :code, id: :associate_code, :required => true, oninvalid: 'this.setCustomValidity("Este campo no debe estar vacío.")', oninput: 'this.setCustomValidity("")' %>
  </div>

 <div class="field">
    <%= form.label 'Posición*' %>
    <%= form.select :position, ["Asociado", "Mayorista", "Equipo del mundo", "GET", "Millonario", "Presidente"], :required => true, oninvalid: 'this.setCustomValidity("Este campo no debe estar vacío.")', oninput: 'this.setCustomValidity("")' %>
  </div>

  <div class="field">
    <%= form.label 'Nombre*' %>
    <%= form.text_field :name, id: :associate_name, :required => true, oninvalid: 'this.setCustomValidity("Este campo no debe estar vacío.")', oninput: 'this.setCustomValidity("")' %>
  </div>

  <div class="field">
    <%= form.label 'Apellido*' %>
    <%= form.text_field :last_name, id: :associate_last_name, :required => true, oninvalid: 'this.setCustomValidity("Este campo no debe estar vacío.")', oninput: 'this.setCustomValidity("")' %>
  </div>

  <div class="field">
    <%= form.label 'Patrocinador*' %>
    <%= form.text_field :sponsor, id: :associate_sponsor, :required => true, oninvalid: 'this.setCustomValidity("Este campo no debe estar vacío.")', oninput: 'this.setCustomValidity("")' %>
  </div>

  <div class="field">
    <%= form.label 'Presidente ascendente*' %>
    <%= form.text_field :ascending_president, id: :associate_ascending_president, :required => true, oninvalid: 'this.setCustomValidity("Este campo no debe estar vacío.")', oninput: 'this.setCustomValidity("")' %>
  </div>

  <div class="field">
    <%= form.label 'Tabulador ascendente*' %>
    <%= form.text_field :ascending_tabulator, id: :associate_ascending_tabulator, :required => true, oninvalid: 'this.setCustomValidity("Este campo no debe estar vacío.")', oninput: 'this.setCustomValidity("")' %>
  </div>

  <div class="actions">
    <%= form.submit 'Crear asociado', class: 'btn btn-success btn-lg btn-block' %>
  </div>
<% end %>
</div>
</body>

app/views/associates/edit.html.erb
<div class="form_title"><h1>Modificar Asociado</h1></div>

<%= render 'form', associate: @associate %>

<%= link_to 'Atrás', associates_path, class: 'btn btn-success btn-lg' %>

app/views/associates/index.html.erb
<p id="notice"><%= notice %></p>

 <body class="background_image">
  <h1>Asociados</h1>


  <table class="table table-sm">
    <thead>
      <tr class="bg-success">
        <th scope="col">Código</th>
        <th scope="col">Nombre</th>
        <th scope="col">Apellido</th>
        <th scope="col">Posición</th>
        <th scope="col">Patrocinador</th>
        <th scope="col">Presidente ascendente  </th>
        <th scope="col">Tabulador ascendente  </th>
        <th scope="col">Último pago  </th>
        <th scope="col">Gestión  </th>
        <th scope="col">  </th>
      </tr>
    </thead>
    <tbody>
      <tbody>
    <% @associates.each do |associate| %>
      <tr class="table-light">
        <td><%= associate.code %></td>
        <td><%= associate.name %></td>
        <td><%= associate.last_name %></td>
        <td><%= associate.position %></td>
        <td><%= associate.sponsor %></td>
        <td><%= associate.ascending_president %></td>
        <td><%= associate.ascending_tabulator %></td>
        <td><%= associate.last_payment %></td>
        <td><%= link_to 'Modificar', edit_associate_path(associate), class: 'btn btn-success btn-lg'  %></td>
        <td><%= button_to 'Eliminar', associate,  data: { confirm: 'Are you sure?' }, method: :delete, class: 'btn btn-success btn-lg' %>   </td>
      </tr>
    <% end %>
    </tbody>
  </table>

   <%= link_to 'Atrás', select_associate_management_path, class: 'btn btn-success btn-lg' %>

</body>

app/views/associates/new.html.erb
<div class="form_title"><h1>Nuevo asociado</h1></div>

<%= render 'form', associate: @associate %>

<%= link_to 'Atrás', select_associate_management_path, class: 'btn btn-success btn-lg' %>

app/views/associates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @associate.code %>
</p>

<p>
  <strong>Name:</strong>
  <%= @associate.name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @associate.last_name %>
</p>

<p>
  <strong>Sponsor:</strong>
  <%= @associate.sponsor %>
</p>

<p>
  <strong>Ascending president:</strong>
  <%= @associate.ascending_president %>
</p>

<p>
  <strong>Ascending tabulator:</strong>
  <%= @associate.ascending_tabulator %>
</p>

<p>
  <strong>Last payment:</strong>
  <%= @associate.last_payment %>
</p>

<%= link_to 'Edit', edit_associate_path(@associate) %> |
<%= link_to 'Back', associates_path %>